function [leaders, followers, topo] = initialize_system(cfg)

    %% 拓扑
    topo.Af = cfg.topology.Af;
    topo.B  = cfg.topology.B;
    topo.Nf = cfg.numFollowers;
    topo.Nl = cfg.numLeaders;

    %% 创建领导者
    leaders(1) = create_leader( ...
        1, ...
        cfg.leaders.p0{1}, ...
        cfg.leaders.v0{1}, ...
        cfg);

    for i = 2:cfg.numLeaders
        leaders(i) = create_leader( ...
            i, ...
            cfg.leaders.p0{i}, ...
            cfg.leaders.v0{i}, ...
            cfg);
    end

    %% 创建跟随者
    followers(1) = create_follower( ...
        1, ...
        cfg.followers.p0{1}, ...
        cfg.followers.v0{1}, ...
        cfg);

    for i = 2:cfg.numFollowers
        followers(i) = create_follower( ...
            i, ...
            cfg.followers.p0{i}, ...
            cfg.followers.v0{i}, ...
            cfg);
    end

end